spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/onsang
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug

#  spring:
#    mvc:
#      pathmatch:
#        matching-strategy: ant_path_matcher